const annoncesData = [
  {
    id: '1',
    title: 'Lys leilighet 2-roms med balkong',
    category: 'Eiendom',
    location: 'Oslo',
    district: 'Majorstuen',
    price: '12 000 kr/måned',
    image: 'https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=800&q=80&auto=format&fit=crop',
    description: 'Renovert studio med balkong, nær butikker og transport.',
    descriptionLong: 'Ideell leilighet for en person eller par. Kjøkken med hvitevarer, moderne bad, bod og stort lyst oppholdsrom. Leies ut møblert og klart for innflytting.',
    age: '2 dager',
    publishedAt: '2026-04-07T09:30:00Z',
    seller: 'Anna Berg',
    condition: 'Nyrenovert',
    tags: ['Balkong', 'Møblert', 'Sentrum'],
  },
  {
    id: '2',
    title: 'UX/UI designer søker oppdrag',
    category: 'Jobber',
    location: 'Oslo',
    district: 'Ekstern',
    price: 'Fra 500 kr/time',
    image: 'https://images.unsplash.com/photo-1529333166437-7750a6dd5a70?w=800&q=80&auto=format&fit=crop',
    description: 'Frilansprofil med 5 års erfaring på nett- og mobilprosjekter.',
    descriptionLong: 'Tilgjengelig for designoppdrag innen produkt, prototyping og grensesnitt. Tilstede i Oslo og Bergen, men jobber også gjerne eksternt for korte eller lange oppdrag.',
    age: '6 timer',
    publishedAt: '2026-04-09T08:00:00Z',
    seller: 'Marius Nilsen',
    condition: 'Tilgjengelig nå',
    tags: ['Figma', 'Produktdesign', 'Remote'],
  },
  {
    id: '3',
    title: 'Elektrisk scooter med ny service',
    category: 'Kjøretøy',
    location: 'Bergen',
    district: 'Årstad',
    price: '15 000 kr',
    image: 'https://images.unsplash.com/photo-1591122519484-70428711810d?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.1.0',
    description: 'Scooter i perfekt stand, rekkevidde opp til 80 km.',
    descriptionLong: 'Selges med lader og hjelm. Nytt batteri, service utført for 3 måneder siden og kvitteringer følger med. Praktisk til pendling i byen.',
    age: '1 uke',
    publishedAt: '2026-04-02T12:30:00Z',
    seller: 'Jonas Lie',
    condition: 'Svært god',
    tags: ['Elektrisk', 'Hjelm inkludert', '80 km'],
  },
  {
    id: '4',
    title: 'Høyt eikebord for kjøkken eller studio',
    category: 'Hjem & Hage',
    location: 'Trondheim',
    district: 'Midtbyen',
    price: '2 400 kr',
    image: 'https://images.unsplash.com/photo-1519710164239-da123dc03ef4?w=800&q=80&auto=format&fit=crop',
    description: 'Høyt eikebord, ideelt for kjøkken eller arbeidsplass.',
    descriptionLong: 'Mål 140x70 cm, moderne design med oljet finish. Passer godt til både spiseplass og kreativt hjemmekontor. Noen få bruksspor.',
    age: '4 dager',
    publishedAt: '2026-04-05T15:45:00Z',
    seller: 'Kaja Solheim',
    condition: 'God',
    tags: ['Massiv eik', '140x70', 'Minimalistisk'],
  },
  {
    id: '5',
    title: 'Gaming bærbar RTX 3060',
    category: 'Elektronikk',
    location: 'Stavanger',
    district: 'Forus',
    price: '8 500 kr',
    image: 'https://images.unsplash.com/photo-1517336714731-489689fd1ca8?w=800&q=80&auto=format&fit=crop',
    description: 'RTX 3060, 16 GB RAM, 512 GB SSD. God stand.',
    descriptionLong: 'Perfekt for gaming, streaming og innholdsskaping. God kjøling, vedlikeholdt batteri og opplyst tastatur. Leveres ferdig nullstilt.',
    age: '12 timer',
    publishedAt: '2026-04-08T20:15:00Z',
    seller: 'Emil Tangen',
    condition: 'Veldig god',
    tags: ['RTX 3060', '16 GB RAM', 'SSD'],
  },
  {
    id: '6',
    title: 'Barnevogn med regntrekk og bag',
    category: 'Hjem & Hage',
    location: 'Oslo',
    district: 'Sagene',
    price: '1 900 kr',
    image: 'https://images.unsplash.com/photo-1515488042361-ee00e0ddd4e4?w=800&q=80&auto=format&fit=crop',
    description: 'Lett og praktisk barnevogn med mye oppbevaring.',
    descriptionLong: 'Kommer med regntrekk, ekstra bag og justerbart håndtak. Enkel å slå sammen og får plass i liten bil. Klar til bruk med én gang.',
    age: '3 dager',
    publishedAt: '2026-04-06T10:10:00Z',
    seller: 'Helene Aas',
    condition: 'God',
    tags: ['Familie', 'Regntrekk', 'Sammenleggbar'],
  },
  {
    id: '7',
    title: 'Sykkelservice hjemme hos deg',
    category: 'Tjenester',
    location: 'Bergen',
    district: 'Sentrum',
    price: 'Fra 650 kr',
    image: 'https://images.unsplash.com/photo-1541625602330-2277a4c46182?w=800&q=80&auto=format&fit=crop',
    description: 'Mobil sykkelmekaniker for vårservice og reparasjoner.',
    descriptionLong: 'Jeg kommer hjem til deg og utfører vask, justering av gir, bremser og enkel feilsøking. Perfekt for deg som vil spare tid.',
    age: '1 dag',
    publishedAt: '2026-04-08T09:00:00Z',
    seller: 'Viktor Hauge',
    condition: 'Ledige tider denne uken',
    tags: ['Hjemmeservice', 'Sykkel', 'Bergen'],
  },
  {
    id: '8',
    title: 'Kompakt bybil, lav kilometerstand',
    category: 'Kjøretøy',
    location: 'Trondheim',
    district: 'Byåsen',
    price: '89 000 kr',
    image: 'https://images.unsplash.com/photo-1503376780353-7e6692767b70?w=800&q=80&auto=format&fit=crop',
    description: 'Drivstoffgjerrig bybil med nylig EU-godkjenning.',
    descriptionLong: 'Perfekt førstebil med gode vinterdekk, servicehefte og lavt forbruk. Enkel å parkere og rimelig i drift.',
    age: '5 dager',
    publishedAt: '2026-04-04T14:20:00Z',
    seller: 'Sara Hoel',
    condition: 'God',
    tags: ['EU-godkjent', 'Vinterdekk', 'Førstebil'],
  },
  {
    id: '9',
    title: 'Senior frontend-utvikler tilgjengelig',
    category: 'Jobber',
    location: 'Stavanger',
    district: 'Ekstern',
    price: 'Fra 850 kr/time',
    image: 'https://images.unsplash.com/photo-1498050108023-c5249f4df085?w=800&q=80&auto=format&fit=crop',
    description: 'React-spesialist for dashboards, design systems og ytelse.',
    descriptionLong: '10 års erfaring med React, TypeScript og komponentbibliotek. Kan bidra både strategisk og hands-on i produktteam eller konsulentoppdrag.',
    age: '8 dager',
    publishedAt: '2026-04-01T07:40:00Z',
    seller: 'Lina Østby',
    condition: 'Åpen for kontrakt',
    tags: ['React', 'TypeScript', 'Design system'],
  },
  {
    id: '10',
    title: 'Speilløst kamera med ekstra objektiv',
    category: 'Elektronikk',
    location: 'Oslo',
    district: 'Grünerløkka',
    price: '6 900 kr',
    image: 'https://images.unsplash.com/photo-1516035069371-29a1b244cc32?w=800&q=80&auto=format&fit=crop',
    description: 'Lett kamera for reise, foto og video i høy kvalitet.',
    descriptionLong: 'Selges med 35 mm objektiv, to batterier og lader. Lite brukt og oppbevart i kamerabag. Perfekt for content creators.',
    age: '9 timer',
    publishedAt: '2026-04-09T05:30:00Z',
    seller: 'Tobias Dahl',
    condition: 'Som ny',
    tags: ['Foto', 'Video', 'Ekstra batteri'],
  },
  {
    id: '11',
    title: 'Moderne hybel nær universitetet',
    category: 'Eiendom',
    location: 'Bergen',
    district: 'Nygård',
    price: '8 700 kr/måned',
    image: 'https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?w=800&q=80&auto=format&fit=crop',
    description: 'Lys hybel med kort vei til campus og kollektiv.',
    descriptionLong: 'Hybel med eget bad, delvis møblert og inkludert internett. Rolig bygg og tilgang til felles vaskerom.',
    age: '18 timer',
    publishedAt: '2026-04-08T12:00:00Z',
    seller: 'Ingrid Mohn',
    condition: 'Innflyttingsklar',
    tags: ['Student', 'Internett inkludert', 'Sentral'],
  },
  {
    id: '12',
    title: 'Flyttehjelp på kvelder og helger',
    category: 'Tjenester',
    location: 'Trondheim',
    district: 'Hele byen',
    price: 'Fra 1 200 kr',
    image: 'https://images.unsplash.com/photo-1600518464441-9154a4dea21b?w=800&q=80&auto=format&fit=crop',
    description: 'To personer med varebil hjelper deg å flytte raskt og trygt.',
    descriptionLong: 'Passer for små og mellomstore flyttinger. Bæring, demontering av enkle møbler og transport kan inkluderes etter avtale.',
    age: '2 uker',
    publishedAt: '2026-03-26T16:50:00Z',
    seller: 'Nord Flytt',
    condition: 'Bookinger åpne',
    tags: ['Varebil', 'Helg', 'Fast pris mulig'],
  },
]

const categoryMetadata = {
  Eiendom: {
    sellerTitle: 'Verifisert utleier',
    responseTime: 'Svarer vanligvis innen 1 time',
    memberSince: 'Medlem siden 2022',
    delivery: 'Visning etter avtale',
    paymentMethods: ['Vipps', 'Bankoverføring'],
    highlights: ['Sentralt område', 'Trygg handel', 'Rask overtakelse'],
    mapLabel: 'Området rundt annonsen',
  },
  Jobber: {
    sellerTitle: 'Profesjonell profil',
    responseTime: 'Svarer vanligvis samme dag',
    memberSince: 'Medlem siden 2021',
    delivery: 'Digital avtale eller fysisk møte',
    paymentMethods: ['Faktura', 'Bankoverføring'],
    highlights: ['Kvalitetssikret profil', 'Portefølje tilgjengelig', 'Fleksibel oppstart'],
    mapLabel: 'Tilgjengelighet og arbeidsområde',
  },
  Kjøretøy: {
    sellerTitle: 'Privat selger',
    responseTime: 'Svarer vanligvis innen 2 timer',
    memberSince: 'Medlem siden 2020',
    delivery: 'Henting på stedet',
    paymentMethods: ['Vipps', 'Bankoverføring'],
    highlights: ['Testkjøring mulig', 'Historikk tilgjengelig', 'Pent vedlikeholdt'],
    mapLabel: 'Område for visning og henting',
  },
  'Hjem & Hage': {
    sellerTitle: 'Lokal selger',
    responseTime: 'Svarer vanligvis innen 3 timer',
    memberSince: 'Medlem siden 2023',
    delivery: 'Henting eller lokal levering',
    paymentMethods: ['Vipps', 'Kontant'],
    highlights: ['Pent brukt', 'Kan reserveres kort', 'Lokal handel'],
    mapLabel: 'Område for levering og henting',
  },
  Elektronikk: {
    sellerTitle: 'Verifisert selger',
    responseTime: 'Svarer vanligvis innen 45 min',
    memberSince: 'Medlem siden 2021',
    delivery: 'Henting eller sending',
    paymentMethods: ['Vipps', 'Bankoverføring'],
    highlights: ['Testet og klar til bruk', 'Trygg betaling', 'God dokumentasjon'],
    mapLabel: 'Område for møte eller levering',
  },
  Tjenester: {
    sellerTitle: 'Tjenesteleverandør',
    responseTime: 'Svarer vanligvis samme dag',
    memberSince: 'Medlem siden 2022',
    delivery: 'Utføres etter avtale',
    paymentMethods: ['Vipps', 'Faktura'],
    highlights: ['Fleksibel avtale', 'Tilgjengelig denne uken', 'Lokalkjent tilbyder'],
    mapLabel: 'Dekningsområde',
  },
}

const annoncesEnriched = annoncesData.map((annonce) => {
  const meta = categoryMetadata[annonce.category] ?? categoryMetadata.Tjenester

  return {
    ...annonce,
    ...meta,
    stats: {
      views: 120 + Number(annonce.id) * 17,
      saves: 10 + Number(annonce.id) * 3,
      shares: 3 + Number(annonce.id),
    },
  }
})

export function useAnnonces() {
  return { annonces: annoncesEnriched }
}

export function getAnnonceById(id) {
  return annoncesEnriched.find((annonce) => annonce.id === id)
}
